name: IPTV Auto Merge & Test (Adaptive)

on:
  schedule:
    - cron: '0 20 * * *'   # 每天凌晨4点(UTC+8)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Merge sources
        run: python scripts/merge.py
      - name: Test streams (Adaptive Mode)
        run: python scripts/test_adaptive.py
      - name: Classify channels
        run: python scripts/classify.py
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Auto update IPTV lists" || echo "No changes"
          git push
